/**
 * Pure filter/sort logic for the Expenses list's Filters + Sort bottom sheets.
 * Framework-free so it can be unit tested without mounting the page.
 */

export type ExpenseKindFilter = "general" | "linked";
export type ExpenseSourceFilter = "manual" | "auto";
export type ExpensePaymentFilter = "cash" | "transfer" | "pos" | "split";

export interface ExpenseFilterState {
  kind: ExpenseKindFilter | null;
  categories: string[];
  payment: ExpensePaymentFilter | null;
  source: ExpenseSourceFilter | null;
  amountMin: number | null;
  amountMax: number | null;
  /** Inclusive local dates as yyyy-MM-dd; sent to the server as the query range. */
  dateFrom: string | null;
  dateTo: string | null;
}

export const EMPTY_EXPENSE_FILTERS: ExpenseFilterState = {
  kind: null, categories: [], payment: null, source: null, amountMin: null, amountMax: null, dateFrom: null, dateTo: null,
};

export type ExpenseSortKey = "newest" | "oldest" | "amountHigh" | "amountLow";
export interface ExpenseSortState {
  key: ExpenseSortKey;
}

export interface FilterableExpense {
  title: string;
  notes?: string | null;
  date: string;
  amount: number;
  inventoryId?: string | null;
  isAutoGenerated?: boolean | null;
  paymentMethod?: string | null;
  category: { name: string };
}

export const KIND_LABELS: Record<ExpenseKindFilter, string> = { general: "General OPEX", linked: "Linked (Sustaining)" };
export const SOURCE_LABELS: Record<ExpenseSourceFilter, string> = { manual: "Logged manually", auto: "Auto-generated" };
export const PAYMENT_LABELS: Record<ExpensePaymentFilter, string> = {
  cash: "Cash", transfer: "Transfer", pos: "POS / Card", split: "Split",
};

export function expenseMatchesFilters<T extends FilterableExpense>(e: T, f: ExpenseFilterState): boolean {
  if (f.kind === "general" && e.inventoryId) return false;
  if (f.kind === "linked" && !e.inventoryId) return false;
  if (f.categories.length > 0 && !f.categories.includes(e.category.name)) return false;
  if (f.payment && (e.paymentMethod || "cash") !== f.payment) return false;
  if (f.source === "auto" && !e.isAutoGenerated) return false;
  if (f.source === "manual" && e.isAutoGenerated) return false;
  if (f.amountMin != null && e.amount < f.amountMin) return false;
  if (f.amountMax != null && e.amount > f.amountMax) return false;
  const day = e.date.slice(0, 10);
  if (f.dateFrom && day < f.dateFrom) return false;
  if (f.dateTo && day > f.dateTo) return false;
  return true;
}

export function expenseMatchesSearch(e: FilterableExpense, term: string): boolean {
  const q = term.trim().toLowerCase();
  if (!q) return true;
  return (
    e.title.toLowerCase().includes(q) ||
    (e.notes ?? "").toLowerCase().includes(q) ||
    e.category.name.toLowerCase().includes(q)
  );
}

export function countActiveExpenseFilters(f: ExpenseFilterState): number {
  return (
    (f.kind ? 1 : 0) +
    (f.categories.length > 0 ? 1 : 0) +
    (f.payment ? 1 : 0) +
    (f.source ? 1 : 0) +
    (f.amountMin != null || f.amountMax != null ? 1 : 0) +
    (f.dateFrom || f.dateTo ? 1 : 0)
  );
}

export function amountSummary(f: Pick<ExpenseFilterState, "amountMin" | "amountMax">, symbol: string): string | null {
  const m = (n: number) => `${symbol}${n.toLocaleString()}`;
  if (f.amountMin != null && f.amountMax != null) return `${m(f.amountMin)} to ${m(f.amountMax)}`;
  if (f.amountMin != null) return `${m(f.amountMin)} or more`;
  if (f.amountMax != null) return `Up to ${m(f.amountMax)}`;
  return null;
}

const fmtDay = (d: string) =>
  new Date(`${d}T00:00:00`).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });

export function expenseDateRangeLabel(from: string | null, to: string | null): string {
  if (from && to) return from === to ? fmtDay(from) : `${fmtDay(from)} – ${fmtDay(to)}`;
  if (from) return `From ${fmtDay(from)}`;
  return to ? `Until ${fmtDay(to)}` : "";
}

export interface ExpenseFilterChip {
  key: "kind" | "categories" | "payment" | "source" | "amount" | "dateRange";
  label: string;
}

export function buildExpenseFilterChips(f: ExpenseFilterState, symbol: string): ExpenseFilterChip[] {
  const chips: ExpenseFilterChip[] = [];
  if (f.kind) chips.push({ key: "kind", label: KIND_LABELS[f.kind] });
  if (f.categories.length > 0) chips.push({ key: "categories", label: f.categories.join(", ") });
  if (f.payment) chips.push({ key: "payment", label: PAYMENT_LABELS[f.payment] });
  if (f.source) chips.push({ key: "source", label: SOURCE_LABELS[f.source] });
  const amount = amountSummary(f, symbol);
  if (amount) chips.push({ key: "amount", label: amount });
  const range = expenseDateRangeLabel(f.dateFrom, f.dateTo);
  if (range) chips.push({ key: "dateRange", label: range });
  return chips;
}

export function clearExpenseFilterChip(f: ExpenseFilterState, key: ExpenseFilterChip["key"]): ExpenseFilterState {
  switch (key) {
    case "kind": return { ...f, kind: null };
    case "categories": return { ...f, categories: [] };
    case "payment": return { ...f, payment: null };
    case "source": return { ...f, source: null };
    case "amount": return { ...f, amountMin: null, amountMax: null };
    case "dateRange": return { ...f, dateFrom: null, dateTo: null };
  }
}

export function expenseSortLabel(sort: ExpenseSortState | null): string {
  if (!sort) return "Sort";
  return {
    newest: "Sort: Newest", oldest: "Sort: Oldest", amountHigh: "Sort: Highest amount", amountLow: "Sort: Lowest amount",
  }[sort.key];
}

export function sortExpenses<T extends FilterableExpense>(rows: T[], sort: ExpenseSortState | null): T[] {
  if (!sort) return rows;
  const time = (e: T) => new Date(e.date).getTime();
  return [...rows].sort((a, b) => {
    switch (sort.key) {
      case "newest": return time(b) - time(a);
      case "oldest": return time(a) - time(b);
      case "amountHigh": return b.amount - a.amount;
      case "amountLow": return a.amount - b.amount;
    }
  });
}
