import { describe, it, expect } from "vitest";
import {
  EMPTY_EXPENSE_FILTERS,
  buildExpenseFilterChips,
  clearExpenseFilterChip,
  countActiveExpenseFilters,
  expenseMatchesFilters,
  expenseMatchesSearch,
  sortExpenses,
} from "./expense-filters";

const x = (title: string, amount: number, date: string, o: Record<string, unknown> = {}) =>
  ({ title, amount, date, category: { name: "Rent" }, ...o });
const rows = [
  x("Shop rent", 50000, "2026-09-01"),
  x("Flour", 8000, "2026-09-20", { inventoryId: "i1", category: { name: "Stock" }, paymentMethod: "transfer" }),
  x("Payroll", 120000, "2026-09-30", { isAutoGenerated: true, category: { name: "Salaries" }, paymentMethod: "split" }),
];
const names = (f: Parameters<typeof expenseMatchesFilters>[1]) => rows.filter((r) => expenseMatchesFilters(r, f)).map((r) => r.title);

describe("expense filters", () => {
  it("matches all when empty", () => expect(names(EMPTY_EXPENSE_FILTERS)).toHaveLength(3));
  it("filters by type, category, payment and source", () => {
    expect(names({ ...EMPTY_EXPENSE_FILTERS, kind: "linked" })).toEqual(["Flour"]);
    expect(names({ ...EMPTY_EXPENSE_FILTERS, kind: "general" })).toEqual(["Shop rent", "Payroll"]);
    expect(names({ ...EMPTY_EXPENSE_FILTERS, categories: ["Stock", "Rent"] })).toEqual(["Shop rent", "Flour"]);
    expect(names({ ...EMPTY_EXPENSE_FILTERS, payment: "cash" })).toEqual(["Shop rent"]);
    expect(names({ ...EMPTY_EXPENSE_FILTERS, source: "auto" })).toEqual(["Payroll"]);
    expect(names({ ...EMPTY_EXPENSE_FILTERS, source: "manual" })).toEqual(["Shop rent", "Flour"]);
  });
  it("filters by amount range", () => {
    expect(names({ ...EMPTY_EXPENSE_FILTERS, amountMin: 10000, amountMax: 60000 })).toEqual(["Shop rent"]);
  });
  it("filters by inclusive date range and chips it", () => {
    const d = rows.map((r) => r.date.slice(0, 10)).sort();
    const f = { ...EMPTY_EXPENSE_FILTERS, dateFrom: d[0], dateTo: d[0] };
    expect(rows.filter((r) => expenseMatchesFilters(r, f)).every((r) => r.date.slice(0, 10) === d[0])).toBe(true);
    expect(countActiveExpenseFilters(f)).toBe(1);
    expect(buildExpenseFilterChips(f, "₦").map((c) => c.key)).toEqual(["dateRange"]);
    expect(clearExpenseFilterChip(f, "dateRange").dateFrom).toBeNull();
  });
  it("searches title, notes and category", () => {
    expect(rows.filter((r) => expenseMatchesSearch(r, "sala")).length).toBe(1);
    expect(rows.filter((r) => expenseMatchesSearch(r, "FLOUR")).length).toBe(1);
  });
  it("counts, builds and clears chips", () => {
    const f = { ...EMPTY_EXPENSE_FILTERS, kind: "general" as const, amountMin: 1000 };
    expect(countActiveExpenseFilters(f)).toBe(2);
    expect(buildExpenseFilterChips(f, "₦").map((c) => c.label)).toEqual(["General OPEX", "₦1,000 or more"]);
    expect(clearExpenseFilterChip(f, "amount").amountMin).toBeNull();
  });
  it("sorts", () => {
    expect(sortExpenses(rows, { key: "newest" })[0].title).toBe("Payroll");
    expect(sortExpenses(rows, { key: "oldest" })[0].title).toBe("Shop rent");
    expect(sortExpenses(rows, { key: "amountHigh" })[0].title).toBe("Payroll");
    expect(sortExpenses(rows, { key: "amountLow" })[0].title).toBe("Flour");
  });
});
