import { sql, relations } from "drizzle-orm";
import { pgTable, text, varchar, boolean, timestamp, unique, index, jsonb, numeric } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { stores } from "./stores";
import { inventory, products, type Inventory } from "./catalog";

// Expense Categories Table
export const expenseCategories = pgTable("expense_categories", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  storeId: varchar("store_id").notNull().references(() => stores.id),
  name: text("name").notNull(),
  isSystem: boolean("is_system").notNull().default(false), // true for Payroll, Rent, etc.
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const expenseCategoriesRelations = relations(expenseCategories, ({ one, many }) => ({
  store: one(stores, {
    fields: [expenseCategories.storeId],
    references: [stores.id],
  }),
  expenses: many(expenses),
}));

export const insertExpenseCategorySchema = createInsertSchema(expenseCategories).omit({ id: true, createdAt: true });
export type InsertExpenseCategory = z.infer<typeof insertExpenseCategorySchema>;
export type ExpenseCategory = typeof expenseCategories.$inferSelect;

// Expenses Table
export const expenses = pgTable("expenses", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  storeId: varchar("store_id").notNull().references(() => stores.id),
  title: text("title").notNull(),
  amount: numeric("amount", { precision: 12, scale: 2 }).$type<number>().notNull().default(0),
  categoryId: varchar("category_id").notNull().references(() => expenseCategories.id),
  inventoryId: varchar("inventory_id").references(() => inventory.id), // legacy single-link — superseded by expense_linked_items
  allocationDriver: text("allocation_driver").notNull().default("count"), // 'count' | 'revenue'
  date: text("date").notNull(), // ISO Date YYYY-MM-DD
  notes: text("notes"),
  receiptUrl: text("receipt_url"),
  // Which door this cost takes into the P&L: 'overhead' -> Operating Expenses,
  // 'direct_supply' -> Direct Supplies & Consumables. Decided by what the cost IS,
  // never by what it is linked to — linking is attribution only.
  costClass: text("cost_class").notNull().default("overhead"),
  backfilledCostClass: boolean("backfilled_cost_class").notNull().default(false), // set by migration 0022
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false), // true if from Payroll module
  paymentMethod: text("payment_method").notNull().default("cash"), // cash, transfer, pos, split, credit
  splitPayments: jsonb("split_payments").$type<Array<{method: string, amount: number}>>(),
  isDeleted: boolean("is_deleted").notNull().default(false),
  deletedAt: timestamp("deleted_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (table) => [
  index("idx_expenses_store_date").on(table.storeId, table.date),
]);

export const expensesRelations = relations(expenses, ({ one }) => ({
  store: one(stores, {
    fields: [expenses.storeId],
    references: [stores.id],
  }),
  category: one(expenseCategories, {
    fields: [expenses.categoryId],
    references: [expenseCategories.id],
  }),
  inventory: one(inventory, {
    fields: [expenses.inventoryId],
    references: [inventory.id],
  }),
}));

export const insertExpenseSchema = createInsertSchema(expenses).omit({ id: true, createdAt: true, updatedAt: true, isAutoGenerated: true }).extend({
  splitPayments: z.array(
    z.object({
      method: z.string(),
      amount: z.number(),
    })
  ).nullable().optional(),
  amount: z.number(),
});
export type InsertExpense = z.infer<typeof insertExpenseSchema>;
export type Expense = typeof expenses.$inferSelect;

export type ExpenseWithCategory = Expense & {
  category: ExpenseCategory;
  inventory?: Inventory | null;
};

// ── Expense Linked Items ──────────────────────────────────────────────────────
// Links an expense to one or more product groups for activity-based allocation.
// The cost split is derived at query time from actual sales data (count/revenue).
export const expenseLinkedItems = pgTable("expense_linked_items", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  expenseId: varchar("expense_id").notNull().references(() => expenses.id, { onDelete: "cascade" }),
  productId: varchar("product_id").notNull().references(() => products.id),
}, (table) => [
  unique("expense_linked_items_unique").on(table.expenseId, table.productId),
]);

export const expenseLinkedItemsRelations = relations(expenseLinkedItems, ({ one }) => ({
  expense: one(expenses, { fields: [expenseLinkedItems.expenseId], references: [expenses.id] }),
  product: one(products, { fields: [expenseLinkedItems.productId], references: [products.id] }),
}));

export type ExpenseLinkedItem = typeof expenseLinkedItems.$inferSelect;
