import { storage } from "../storage";
import { db } from "../db";
import { eq, and, gte, lte, gt, sql, or, inArray } from "drizzle-orm";
import { checkouts, orders, creditEntries, repayments, orderConsumables, settings } from "@shared/schema";
import { getStoreTimezone, toUtcStart, toUtcEnd } from "../lib/dateUtils";
import { DEFAULT_LOYALTY_POINT_VALUE } from "@shared/analytics/constants";

export class AnalyticsService {
  /**
   * Total realized loss on credit entries written off in the given date range,
   * net of any repayments received before write-off. Batches the repayment
   * lookup across all written-off entries instead of querying per-entry.
   */
  private async getWrittenOffBadDebtTotal(
    storeId: string,
    startDate?: string,
    endDate?: string
  ): Promise<number> {
    const tz = await getStoreTimezone(storeId);
    const writtenOffEntries = await db
      .select({
        id: creditEntries.id,
        amountOwed: creditEntries.amountOwed,
        amountPaidUpfront: creditEntries.amountPaidUpfront,
      })
      .from(creditEntries)
      .where(
        and(
          eq(creditEntries.storeId, storeId),
          eq(creditEntries.status, "written_off"),
          startDate ? gte(creditEntries.updatedAt, toUtcStart(startDate, tz)) : sql`true`,
          endDate ? lte(creditEntries.updatedAt, toUtcEnd(endDate, tz)) : sql`true`
        )
      );

    if (writtenOffEntries.length === 0) return 0;

    const entryIds = writtenOffEntries.map((e) => e.id);
    const repaymentTotals = await db
      .select({
        creditEntryId: repayments.creditEntryId,
        total: sql<number>`sum(${repayments.amountReceived})`,
      })
      .from(repayments)
      .where(inArray(repayments.creditEntryId, entryIds))
      .groupBy(repayments.creditEntryId);

    const repaidByEntry = new Map(
      repaymentTotals.map((r) => [r.creditEntryId, parseFloat(String(r.total || 0))])
    );

    return writtenOffEntries.reduce((total, entry) => {
      const repaid = repaidByEntry.get(entry.id) || 0;
      const originalOwed = entry.amountOwed - entry.amountPaidUpfront;
      return total + Math.max(0, originalOwed - repaid);
    }, 0);
  }

  /**
   * Computes P&L summary metrics
   */
  public async getProfitLossSummary(
    storeId: string,
    startDate?: string,
    endDate?: string
  ): Promise<any> {
    const {
      serviceRevenue,
      productRevenue,
      grossRevenue,
      returnedRevenue,
      totalRevenue,
      costOfGoodsSold,
      grossProfit,
      discountsGiven,
      discountsList,
    } = await storage.getProfitLossSummary(storeId, startDate, endDate);

    // EVERY non-deleted expense, partitioned by cost class.
    //
    // This used to ask for "general" expenses only — meaning those with no item
    // link — which silently deleted every linked expense from the statement.
    // Linking is attribution, not costing: it decides which item a cost is
    // reported against, never whether it is counted.
    const expenseList = await storage.getExpenses(storeId, startDate, endDate, "all");

    const totalBadDebt = await this.getWrittenOffBadDebtTotal(storeId, startDate, endDate);

    let totalOperationalExpenses = totalBadDebt;
    let directSuppliesFromExpenses = 0;
    const expensesByCategory: Record<string, number> = {};
    const directSuppliesByCategory: Record<string, number> = {};

    if (totalBadDebt > 0) {
      expensesByCategory["Bad Debt — Written Off"] = totalBadDebt;
    }

    expenseList.forEach((e) => {
      // Wages are recognised from paid payroll periods below. The Payroll module
      // also writes a mirror expense row, so counting both would double the wage
      // bill. The discriminator is the system category, not isAutoGenerated.
      if (e.category?.isSystem && e.category?.name === "Payroll") return;

      const amount = Number(e.amount);
      const catName = e.category?.name || "Uncategorized";

      if ((e as any).costClass === "direct_supply") {
        directSuppliesFromExpenses += amount;
        directSuppliesByCategory[catName] = (directSuppliesByCategory[catName] || 0) + amount;
      } else {
        totalOperationalExpenses += amount;
        expensesByCategory[catName] = (expensesByCategory[catName] || 0) + amount;
      }
    });

    const expensesGrouped = Object.entries(expensesByCategory).map(([category, amount]) => ({
      category,
      amount,
    }));
    const directSuppliesGrouped = Object.entries(directSuppliesByCategory).map(([category, amount]) => ({
      category,
      amount,
    }));

    // Consumables drawn down by recipes when services were delivered. Liveness is
    // derived through the checkouts join, so voided sales drop out on their own
    // and a partial return correctly leaves the full original cost standing.
    const directSuppliesFromRecipes = await this.getRecipeConsumableCost(storeId, startDate, endDate);
    const directSuppliesTotal = directSuppliesFromExpenses + directSuppliesFromRecipes;

    // Fetch overlapping paid payroll periods via storage
    const payrollDetails = await storage.getPaidPayrollExpenses(storeId, startDate, endDate);
    const totalPayrollExpenses = payrollDetails.reduce((sum, p) => sum + p.amount, 0);

    const totalExpenses =
      totalOperationalExpenses + directSuppliesTotal + totalPayrollExpenses + discountsGiven;
    const operatingProfit = grossProfit - totalExpenses;

    return {
      serviceRevenue,
      productRevenue,
      grossRevenue,
      returnedRevenue,
      totalRevenue,
      costOfGoodsSold,
      grossProfit,
      discountsGiven,
      discountsList,
      totalOperationalExpenses,
      directSuppliesFromExpenses,
      directSuppliesFromRecipes,
      directSuppliesTotal,
      directSuppliesGrouped,
      // Memo line: what delivery actually costs. Gross profit deliberately keeps
      // its old meaning (revenue - item cost) so margin history stays comparable,
      // which makes this the figure to read for true delivery margin.
      costOfDelivery: costOfGoodsSold + directSuppliesTotal,
      totalPayrollExpenses,
      totalExpenses,
      operatingProfit,
      expensesGrouped,
      payrollDetails,
    };
  }

  /**
   * Consumable cost released by recipes in the period: SUM(order_consumables.total_cost)
   * over completed, non-voided checkouts.
   *
   * The date comes from the checkout, not from order_consumables — an addendum
   * writes its checkout with the ORIGINAL sale date, so this lands the cost in the
   * period the service was actually delivered.
   */
  private async getRecipeConsumableCost(
    storeId: string,
    startDate?: string,
    endDate?: string
  ): Promise<number> {
    const tz = await getStoreTimezone(storeId);
    const [row] = await db
      .select({ total: sql<string>`COALESCE(SUM(${orderConsumables.totalCost}::numeric), 0)` })
      .from(orderConsumables)
      .innerJoin(orders, eq(orders.id, orderConsumables.orderId))
      .innerJoin(checkouts, eq(checkouts.orderId, orders.id))
      .where(
        and(
          eq(orderConsumables.storeId, storeId),
          eq(checkouts.paymentStatus, "completed"),
          eq(checkouts.isVoided, false),
          startDate ? gte(checkouts.createdAt, toUtcStart(startDate, tz)) : sql`true`,
          endDate ? lte(checkouts.createdAt, toUtcEnd(endDate, tz)) : sql`true`
        )
      );
    return Number(row?.total ?? 0);
  }

  /**
   * The same figure as getRecipeConsumableCost, broken down by the item that
   * CONSUMED the supply (orders.inventory_id) rather than by the supply itself —
   * "which service burns the most product?" is the question owners ask.
   *
   * Summing this map and adding the unallocated bucket must reproduce the P&L's
   * Direct Supplies line exactly; that is the reconciliation invariant.
   */
  private async getRecipeConsumableCostByItem(
    storeId: string,
    startDate?: string,
    endDate?: string
  ): Promise<Map<string, number>> {
    const tz = await getStoreTimezone(storeId);
    const rows = await db
      .select({
        inventoryId: orders.inventoryId,
        total: sql<string>`COALESCE(SUM(${orderConsumables.totalCost}::numeric), 0)`,
      })
      .from(orderConsumables)
      .innerJoin(orders, eq(orders.id, orderConsumables.orderId))
      .innerJoin(checkouts, eq(checkouts.orderId, orders.id))
      .where(
        and(
          eq(orderConsumables.storeId, storeId),
          eq(checkouts.paymentStatus, "completed"),
          eq(checkouts.isVoided, false),
          startDate ? gte(checkouts.createdAt, toUtcStart(startDate, tz)) : sql`true`,
          endDate ? lte(checkouts.createdAt, toUtcEnd(endDate, tz)) : sql`true`
        )
      )
      .groupBy(orders.inventoryId);

    return new Map(rows.map((r) => [r.inventoryId, Number(r.total)]));
  }

  /**
   * Computes detailed Service and Product profitability matrix
   */
  public async getServiceProfitability(
    storeId: string,
    startDate?: string,
    endDate?: string
  ): Promise<any> {
    // 1. Fetch all inventory items and their parent products for this store
    const items = await storage.getInventory(storeId);
    const productList = await storage.getProducts(storeId);
    const productNameMap = new Map<string, string>(productList.map((p: any) => [p.id, p.name]));

    // 2. Fetch completed checkouts and their orders in the range
    const checkoutConditions: any[] = [
      eq(checkouts.storeId, storeId),
      eq(checkouts.paymentStatus, "completed"),
      eq(checkouts.isVoided, false),
    ];
    const tz2 = await getStoreTimezone(storeId);
    if (startDate) checkoutConditions.push(gte(checkouts.createdAt, toUtcStart(startDate, tz2)));
    if (endDate) checkoutConditions.push(lte(checkouts.createdAt, toUtcEnd(endDate, tz2)));

    const sales = await db
      .select({
        inventoryId: orders.inventoryId,
        quantity: orders.quantity,
        returnedQuantity: orders.returnedQuantity,
        refundedAmount: orders.refundedAmount,
        totalPrice: orders.totalPrice,
      })
      .from(orders)
      .innerJoin(checkouts, eq(orders.id, checkouts.orderId))
      .where(and(...checkoutConditions));

    // 3. Expenses in the period, split by what they ARE and what they point at.
    //
    // Class decides the P&L door; links decide only which item a cost is reported
    // against. So only direct_supply expenses become per-item sustaining costs, and
    // a direct_supply expense with no link cannot silently vanish — it lands in
    // unallocatedDirectSupply so the per-item figures still reconcile to the
    // statement's Direct Supplies line.
    const periodExpenses = await storage.getExpenses(storeId, startDate, endDate, "all") as any[];
    const isPayrollMirror = (e: any) => e.category?.isSystem && e.category?.name === "Payroll";
    const isLinked = (e: any) => !!e.inventoryId || (e.linkedProducts?.length ?? 0) > 0;

    const directSupplyExpenses = periodExpenses.filter(
      (e) => e.costClass === "direct_supply" && !isPayrollMirror(e),
    );
    const allLinkedExpenses = directSupplyExpenses.filter(isLinked);
    const unallocatedDirectSupply = directSupplyExpenses
      .filter((e) => !isLinked(e))
      .reduce((sum, e) => sum + Number(e.amount), 0);

    // Recipe consumables per consuming item, so a service that burns shampoo shows
    // that cost against itself rather than in a lump.
    const recipeCostByItem = await this.getRecipeConsumableCostByItem(storeId, startDate, endDate);

    // Pre-compute sales weights at BOTH grains.
    //
    // Expenses are linked to a product GROUP, but this report is per VARIANT and
    // the route above it re-groups by product and sums. Allocating only to the
    // group and then reading that figure once per variant multiplied every
    // sustaining cost by the product's variant count — a 3-variant product
    // reported 3x its real cost. Allocating down to the variant means the
    // re-grouping reconstitutes exactly the product total, which is what lets the
    // per-item report reconcile to the P&L.
    const productSalesCount = new Map<string, number>();
    const productSalesRevenue = new Map<string, number>();
    const itemSalesCount = new Map<string, number>();
    const itemSalesRevenue = new Map<string, number>();
    const variantsByProduct = new Map<string, string[]>();

    for (const item of items) {
      const itemSales = sales.filter(s => s.inventoryId === item.id);
      const pid = item.productId;
      const cnt = itemSales.reduce((s, r) => s + Math.max(0, r.quantity - (r.returnedQuantity || 0)), 0);
      const rev = itemSales.reduce((s, r) => s + Math.max(0, r.totalPrice - (r.refundedAmount || 0)), 0);
      productSalesCount.set(pid, (productSalesCount.get(pid) ?? 0) + cnt);
      productSalesRevenue.set(pid, (productSalesRevenue.get(pid) ?? 0) + rev);
      itemSalesCount.set(item.id, cnt);
      itemSalesRevenue.set(item.id, rev);
      variantsByProduct.set(pid, [...(variantsByProduct.get(pid) ?? []), item.id]);
    }

    // sustainingMap / breakdownMap are keyed by INVENTORY ID (variant).
    const sustainingMap = new Map<string, number>();
    const breakdownMap  = new Map<string, { title: string; amount: number; percent: number }[]>();

    for (const exp of allLinkedExpenses) {
      const linked: { productId: string; productName: string }[] = exp.linkedProducts ?? [];

      // Legacy single-link: fall back to inventoryId → productId
      let linkedProductIds: string[] = linked.map(l => l.productId);
      if (linkedProductIds.length === 0 && exp.inventoryId) {
        const legacyItem = items.find(i => i.id === exp.inventoryId);
        if (legacyItem) linkedProductIds = [legacyItem.productId];
      }
      if (linkedProductIds.length === 0) continue;

      // Compute weight for each linked product
      const driver = exp.allocationDriver ?? "count";
      const weightOfItem = (id: string) =>
        driver === "revenue" ? (itemSalesRevenue.get(id) ?? 0) : (itemSalesCount.get(id) ?? 0);
      const weights = linkedProductIds.map(pid =>
        driver === "revenue"
          ? (productSalesRevenue.get(pid) ?? 0)
          : (productSalesCount.get(pid) ?? 0)
      );
      const totalWeight = weights.reduce((a, b) => a + b, 0);

      linkedProductIds.forEach((pid, idx) => {
        // If total weight is zero (nothing sold yet) fall back to equal share
        const share = totalWeight > 0 ? weights[idx] / totalWeight : 1 / linkedProductIds.length;
        const allocated = Number(exp.amount) * share;

        // Second split, product -> its variants, using the same driver. Equal
        // shares when the product sold nothing, mirroring the rule above.
        const variantIds = variantsByProduct.get(pid) ?? [];
        if (variantIds.length === 0) return;

        const variantWeights = variantIds.map(weightOfItem);
        const variantTotal = variantWeights.reduce((a, b) => a + b, 0);

        variantIds.forEach((invId, vIdx) => {
          const variantShare = variantTotal > 0 ? variantWeights[vIdx] / variantTotal : 1 / variantIds.length;
          const variantAllocated = allocated * variantShare;
          if (variantAllocated === 0 && variantTotal > 0) return;

          sustainingMap.set(invId, (sustainingMap.get(invId) ?? 0) + variantAllocated);

          if (!breakdownMap.has(invId)) breakdownMap.set(invId, []);
          breakdownMap.get(invId)!.push({
            title: exp.title,
            amount: variantAllocated,
            // Share of the whole expense that landed on this variant.
            percent: Math.round(share * variantShare * 100),
          });
        });
      });
    }

    // 4. Group calculations per item
    const itemSummaries = items.map((item) => {
      const itemSales = sales.filter((s) => s.inventoryId === item.id);
      const revenue = itemSales.reduce((sum, s) => sum + Math.max(0, s.totalPrice - (s.refundedAmount || 0)), 0);
      const quantitySold = itemSales.reduce((sum, s) => sum + Math.max(0, s.quantity - (s.returnedQuantity || 0)), 0);
      const cogs = quantitySold * (item.costPrice ?? 0);
      const grossProfit = revenue - cogs;
      const grossProfitMargin = revenue > 0 ? (grossProfit / revenue) * 100 : 0;

      // Keyed by variant, not product — see the allocation loop above.
      const allocatedExpenseCost = sustainingMap.get(item.id) ?? 0;
      const recipeConsumableCost = recipeCostByItem.get(item.id) ?? 0;
      const sustainingCosts = allocatedExpenseCost + recipeConsumableCost;
      const sustainingBreakdown = [...(breakdownMap.get(item.id) ?? [])];
      if (recipeConsumableCost > 0) {
        sustainingBreakdown.push({ title: "Recipe consumables", amount: recipeConsumableCost, percent: 100 });
      }
      const netProfit = grossProfit - sustainingCosts;
      const netProfitMargin = revenue > 0 ? (netProfit / revenue) * 100 : 0;
      const status = netProfit > 0 ? "profit" : netProfit < 0 ? "loss" : "breakeven";

      return {
        id: item.id,
        productId: item.productId,
        productName: productNameMap.get(item.productId) || item.name,
        name: item.name,
        type: item.type,
        revenue,
        quantitySold,
        cogs,
        grossProfit,
        grossProfitMargin,
        sustainingCosts,
        allocatedExpenseCost,
        recipeConsumableCost,
        sustainingBreakdown,
        netProfit,
        netProfitMargin,
        status,
      };
    });

    const services = itemSummaries.filter((s) => s.type === "service");
    const products = itemSummaries.filter((s) => s.type === "product");

    // 5. Overheads — by COST CLASS, not by whether the expense happens to be
    //    linked. An overhead attributed to an item is still an overhead.
    const overheadExpenses = periodExpenses.filter(
      (e) => e.costClass !== "direct_supply" && !isPayrollMirror(e),
    );

    const totalBadDebtProfit = await this.getWrittenOffBadDebtTotal(storeId, startDate, endDate);

    const overheadsByCategory: Record<string, number> = {};

    if (totalBadDebtProfit > 0) {
      overheadsByCategory["Bad Debt — Written Off"] = totalBadDebtProfit;
    }

    overheadExpenses.forEach((e) => {
      const catName = e.category?.name || "Uncategorized";
      overheadsByCategory[catName] = (overheadsByCategory[catName] || 0) + Number(e.amount);
    });
    const generalOverheads = Object.entries(overheadsByCategory).map(([category, amount]) => ({
      category,
      amount,
    }));
    const totalGeneralOverhead =
      overheadExpenses.reduce((sum, e) => sum + Number(e.amount), 0) + totalBadDebtProfit;

    // 6. Paid payroll periods in range
    const payrollDetails = await storage.getPaidPayrollExpenses(storeId, startDate, endDate);
    const totalPayroll = payrollDetails.reduce((sum, p) => sum + p.amount, 0);

    // 7. Discounts given in range (basket + loyalty point redemptions)
    //
    // Grouped by receipt, not by checkout row: `checkouts` holds one row per LINE
    // and replicates the basket discount onto each of them, so summing the raw
    // rows multiplied every multi-line discount by its line count. That inflated
    // totalDiscounts and, since it is subtracted below, understated operatingProfit.
    const discountConditions: any[] = [
      eq(checkouts.storeId, storeId),
      eq(checkouts.paymentStatus, "completed"),
      eq(checkouts.isVoided, false),
    ];
    const tz4 = await getStoreTimezone(storeId);
    if (startDate) discountConditions.push(gte(checkouts.createdAt, toUtcStart(startDate, tz4)));
    if (endDate) discountConditions.push(lte(checkouts.createdAt, toUtcEnd(endDate, tz4)));

    const uniqueTxDiscounts = await db
      .select({
        discountAmount: sql<number>`max(${checkouts.discountAmount})`,
        pointsRedeemed: sql<number>`max(${checkouts.pointsRedeemed})`,
      })
      .from(checkouts)
      .where(and(...discountConditions))
      .groupBy(checkouts.receiptNumber)
      .having(
        or(
          gt(sql`max(${checkouts.discountAmount})`, 0),
          gt(sql`max(${checkouts.pointsRedeemed})`, 0),
        ),
      );
    const [storeSettingsRow] = await db.select().from(settings).where(eq(settings.storeId, storeId));
    const loyaltyPointValue = storeSettingsRow?.loyaltyPointValue ?? DEFAULT_LOYALTY_POINT_VALUE;
    const totalDiscounts = uniqueTxDiscounts.reduce((sum, d) => sum + (Number(d.discountAmount) || 0) + ((Number(d.pointsRedeemed) || 0) * loyaltyPointValue), 0);

    // Final dynamic calculations
    const totalNetProfit = itemSummaries.reduce((sum, s) => sum + s.netProfit, 0);
    const operatingProfit =
      totalNetProfit - unallocatedDirectSupply - totalGeneralOverhead - totalPayroll - totalDiscounts;

    // Reconciliation handle: this must equal the P&L's directSuppliesTotal. Every
    // naira of direct supply is either allocated to an item or sitting in the
    // unallocated bucket — never dropped, never counted twice.
    const totalDirectSupply =
      itemSummaries.reduce((sum, s) => sum + s.sustainingCosts, 0) + unallocatedDirectSupply;

    return {
      services,
      products,
      generalOverheads,
      totalGeneralOverhead,
      unallocatedDirectSupply,
      totalDirectSupply,
      payrollDetails,
      totalPayroll,
      totalDiscounts,
      totalNetProfit,
      operatingProfit,
    };
  }
}

export const analyticsService = new AnalyticsService();
