import { expenses, expenseCategories, inventory, type Inventory } from "@shared/schema";
import { eq, and } from "drizzle-orm";

/** System expense categories this module owns. Auto-created on first use. */
export const SUPPLY_PURCHASE_CATEGORY = "Supplies & Consumables";
export const SUPPLY_VARIANCE_CATEGORY = "Supply Usage Variance";

/**
 * Costing mode for a supply.
 *
 *  expensed — the purchase is charged straight to Direct Supplies. Stock is still
 *             tracked so low-stock alerts fire; it is simply never metered per
 *             service. This is the honest default: most consumables are shared
 *             across dozens of transactions at a rate nobody has measured, and
 *             pretending otherwise means inventing a number.
 *
 *  metered  — the purchase capitalises into stock and cost is released as a recipe
 *             consumes it, with a periodic count settling whatever the estimate
 *             got wrong.
 *
 * These are mutually exclusive by construction: charging on purchase AND releasing
 * via a recipe would count the same naira twice, which is exactly what the whole
 * "one door into the P&L" invariant exists to prevent.
 */
export type CostingMode = "expensed" | "metered";

export function isExpensedSupply(item: Pick<Inventory, "type" | "costingMode">): boolean {
  return item.type === "supply" && (item.costingMode ?? "expensed") === "expensed";
}

export function isMeteredSupply(item: Pick<Inventory, "type" | "costingMode">): boolean {
  return item.type === "supply" && item.costingMode === "metered";
}

/** Find or create a system expense category, inside the caller's transaction. */
export async function ensureSystemCategory(tx: any, storeId: string, name: string): Promise<string> {
  const [existing] = await tx
    .select()
    .from(expenseCategories)
    .where(and(
      eq(expenseCategories.storeId, storeId),
      eq(expenseCategories.name, name),
      eq(expenseCategories.isSystem, true),
    ))
    .limit(1);
  if (existing) return existing.id;

  const [created] = await tx
    .insert(expenseCategories)
    .values({ storeId, name, isSystem: true })
    .returning();
  return created.id;
}

/**
 * Charges a supply purchase to Direct Supplies, for `expensed` supplies only.
 *
 * Runs INSIDE the caller's transaction on purpose. The payroll mirror is written
 * best-effort because losing it only loses a duplicate; losing this one would
 * capitalise a cost that was supposed to be expensed, so it must roll back with
 * the restock that caused it.
 *
 * Returns the amount charged, or 0 when the item is not an expensed supply.
 */
export async function postSupplyPurchaseExpense(
  tx: any,
  params: {
    storeId: string;
    item: Inventory;
    quantityAdded: number;
    unitCost: number;
    date: string; // store-local YYYY-MM-DD
    reference?: string;
  },
): Promise<number> {
  if (!isExpensedSupply(params.item)) return 0;

  // A negative quantity is a correction (stock transfer out, reversal). Charging
  // a negative purchase would credit cost back, which is right, but a zero is a
  // no-op either way.
  const amount = Math.round((params.quantityAdded * params.unitCost + Number.EPSILON) * 100) / 100;
  if (amount === 0) return 0;

  const categoryId = await ensureSystemCategory(tx, params.storeId, SUPPLY_PURCHASE_CATEGORY);

  await tx.insert(expenses).values({
    storeId: params.storeId,
    categoryId,
    title: `Supply purchase — ${params.item.name}`,
    amount,
    date: params.date,
    costClass: "direct_supply",
    isAutoGenerated: true,
    // Money really did leave for this, unlike the usage variance in
    // settleSupplyVariance. Supply purchases previously never reached the cash
    // flow statement at all, because restock creates no expense row; for expensed
    // supplies this closes that gap.
    paymentMethod: "cash",
    notes: params.reference ? `Auto-generated from ${params.reference}` : null,
  } as any);

  return amount;
}

/**
 * Switches a supply between costing modes, truing up the stock already on hand.
 *
 * This adjustment is the whole reason switching is not a plain column update.
 * Under `expensed`, everything on the shelf has ALREADY been charged to the P&L.
 * Flip to `metered` without doing anything and a recipe would release that same
 * cost a second time. So:
 *
 *   expensed -> metered   credit back (qty x cost). The shelf becomes an asset
 *                         again, and the recipe releases it exactly once.
 *   metered  -> expensed   charge (qty x cost). The shelf was an asset that will
 *                         now never be released by a recipe, so it is expensed now.
 *
 * Either way the running total of cost recognised is unchanged by the switch
 * itself — which is the property that makes it safe to change your mind.
 */
export async function switchCostingMode(
  tx: any,
  params: { storeId: string; item: Inventory; to: CostingMode; date: string },
): Promise<{ adjustment: number }> {
  const from: CostingMode = (params.item.costingMode ?? "expensed") as CostingMode;
  if (from === params.to) return { adjustment: 0 };

  const onHandValue =
    Math.round((Number(params.item.quantity) * Number(params.item.costPrice) + Number.EPSILON) * 100) / 100;

  // metered -> expensed charges the shelf; expensed -> metered credits it back.
  const adjustment = params.to === "expensed" ? onHandValue : -onHandValue;

  if (adjustment !== 0) {
    const categoryId = await ensureSystemCategory(tx, params.storeId, SUPPLY_PURCHASE_CATEGORY);
    await tx.insert(expenses).values({
      storeId: params.storeId,
      categoryId,
      title:
        params.to === "expensed"
          ? `Stock on hand expensed — ${params.item.name}`
          : `Stock on hand capitalised — ${params.item.name}`,
      amount: adjustment,
      date: params.date,
      costClass: "direct_supply",
      isAutoGenerated: true,
      // No money moves when you change your mind about how to cost something.
      paymentMethod: "non_cash",
      notes: `Costing mode changed from ${from} to ${params.to}`,
    } as any);
  }

  await tx.update(inventory).set({ costingMode: params.to }).where(eq(inventory.id, params.item.id));

  return { adjustment };
}

/**
 * Settles a metered supply against a physical count. THIS is the mechanism that
 * makes a guessed recipe rate safe to use.
 *
 * A recipe only ever estimates. What is actually known is what was bought (exact)
 * and what is left (countable), so:
 *
 *     really consumed = opening + purchases − closing
 *
 * The count tells us the closing figure, and `inventory.quantity` tells us what the
 * recipes THOUGHT was left. The gap between them is cost the recipe missed (or
 * over-charged), and posting it here means:
 *
 *     over any period bounded by two counts, total supply cost recognised equals
 *     exactly what was consumed — WHATEVER the rate was.
 *
 * The rate only decides how cost is spread across days and which service wears it.
 * That is the whole design: you never have to know how far a bottle goes.
 *
 * Both directions matter. A count showing MORE on hand than expected means the rate
 * over-stated usage, and posts a credit — without that, an estimate could only ever
 * ratchet cost upward.
 */
export async function settleSupplyVariance(
  tx: any,
  params: {
    storeId: string;
    item: Inventory;
    systemQuantity: number;   // what the recipes thought was left
    physicalQuantity: number; // what was actually counted
    date: string;
    reference?: string;
  },
): Promise<number> {
  if (!isMeteredSupply(params.item)) return 0;

  // Negative variance = less on hand than expected = more was used than accrued,
  // so cost is owed. Hence the sign flip.
  const missing = params.systemQuantity - params.physicalQuantity;
  const amount = Math.round((missing * Number(params.item.costPrice) + Number.EPSILON) * 100) / 100;
  if (amount === 0) return 0;

  const categoryId = await ensureSystemCategory(tx, params.storeId, SUPPLY_VARIANCE_CATEGORY);

  await tx.insert(expenses).values({
    storeId: params.storeId,
    categoryId,
    title:
      amount > 0
        ? `Supply used beyond recipe — ${params.item.name}`
        : `Supply over-accrued by recipe — ${params.item.name}`,
    amount,
    date: params.date,
    costClass: "direct_supply",
    isAutoGenerated: true,
    // No money moves here. The cash left when the supply was bought; this is an
    // accrual correction, so it must stay out of cash outflow.
    paymentMethod: "non_cash",
    notes: params.reference ?? null,
  } as any);

  return amount;
}

/** Store-local YYYY-MM-DD, matching how `expenses.date` is written everywhere. */
export function localDateString(timezone: string, when: Date = new Date()): string {
  try {
    return new Intl.DateTimeFormat("en-CA", {
      timeZone: timezone,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    }).format(when);
  } catch {
    return when.toISOString().slice(0, 10);
  }
}
